add pull steps

diff --git a/.github/workflows/jekyll-cicd.yml b/.github/workflows/jekyll-cicd.yml
--- a/.github/workflows/jekyll-cicd.yml
+++ b/.github/workflows/jekyll-cicd.yml
@@ -45,6 +45,9 @@ jobs:
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
 
+    - name: Set build status
+      run: echo "BUILD_STATUS=success" >> $GITHUB_ENV
+
   deploy:
     if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
     environment:
@@ -62,6 +65,21 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - name: Check build success
+      - name: Check build status
         run: |
-          echo "Pull request build completed successfully."
+          if [[ "${{ needs.build.result }}" == "success" ]]; then
+            echo "Build succeeded"
+            exit 0
+          else
+            echo "Build failed"
+            exit 1
+          fi
+
+      - name: PR Build Status
+        run: |
+          if [[ "${{ needs.build.result }}" == "success" ]]; then
+            echo "Pull request build completed successfully."
+          else
+            echo "Pull request build failed."
+            exit 1
+          fi
